### ISSUE TITLE
Improve compilation time of apps using this library

### ISSUE THREAD

**Issue by Raiszo** [PruvoNet/squiss-ts#119]
**Is your feature request related to a problem? Please describe.**
When compiling an application that uses squiss-ts a couple of seconds are invested into "creating source files" for several aws-sdk definition files that are not `SQS` or `S3` related. Traces were generated by using `tsc --generateTrace` and then visualized in chrome.

![image](https://user-images.githubusercontent.com/6730653/187246594-239243bf-ea16-4d55-a1ab-f02272550025.png)
Here more than 2.5 seconds are spent with aws-sdk definition files that are not used by squiss-ts. I have a [repo](https://github.com/Raiszo/repro-squiss-aws-imports) that details on the setup to get this trace

**Describe the solution you'd like**
I think that changing how aws-sdk modules are imported should be enough. 
```typescript 
// import individual service
import S3 from 'aws-sdk/clients/s3';
```

**Describe alternatives you've considered**
Migrating to aws-sdk v3 is not an easy option.

**Additional context**
node: v16.14.0
npm: 8.3.1
typescript: 4.8.2

**Comment by regevbr** [comment]
Cool! would you mind drafting a pr?
