### ISSUE TITLE
xml2js is vulnerable to prototype pollution

### ISSUE THREAD

**Issue by bursache** [PruvoNet/squiss-ts#128]
## Expected Behavior
aws-sdk dependency should accept patches.

## Current Behavior
aws-sdk dependency is listed with a [fixed version](https://github.com/PruvoNet/squiss-ts/blob/master/package.json#L51) that has a direct depedency to xml2js which is vulnerable to prototpye pollution. aws-sdk has been patched here: https://github.com/aws/aws-sdk-js/pull/4389

## Steps to Reproduce (for bugs)
npm install
npm audit --registry=https://registry.npmjs.org/ 
OR 
npx better-npm-audit audit --level=high --registry=https://registry.npmjs.org/

**Comment by regevbr** [comment]
fixed in https://github.com/PruvoNet/squiss-ts/releases/tag/v5.0.0
