### ISSUE TITLE
timeout event handler?

### ISSUE THREAD

**Issue by upugo-dev** [PruvoNet/squiss-ts#24]
Hi,

Looking at using this library, its awesome!

I have a use-case:

We have an sqs-processor that involves booting up Puppeteer and google lighthouse to audit webpages. The processing time varies wildly, and sometimes the program hangs, hence I have been using (in my own manual implementation) a timer that repeatedly extends the message visibility up to a certain limit. With this library, I can now use the `autoExtendTimeout` feature which is awesome!

However, there's a problem; when the message reaches it's hard time limit (i.e. `noExtensionsAfterSecs`) I need to capture this event, so that I can shut down the Puppeteer browser and lighthouse processes - i.e. actually stop the message processing. As far as I can tell, when the `noExtensionsAfterSecs` limit is reached, the message is simply returned to the queue, i.e. effectively calling `release()` on it?

It would be awesome if I could capture this event with a listener so I can do as I please on a timeout event.

I've been looking at `poller.on('handled')...` to see if there is anything I can grab from there, but it doesn't look like the `handled` event is fired in this case.

**Comment by regevbr** [comment]
Hi @upugo-dev

Glad to hear you can make a good use of this library!

You have a `timeoutReached` event being sent on both the message itslef and on the Squiss class exactly for that use case.
https://github.com/PruvoNet/squiss-ts/blob/51ebc20da78ad67e4d2b087d8d348c92a547d93a/src/TimeoutExtender.ts#L181-L182

Does that suits your needs?

I will be heppy to further assist you with anything you need!

**Comment by upugo-dev** [comment]
Hey @regevbr thanks so much for the reply! 

This works great, thank you! 

Could I request you document this? I'd be happy to PR the docs

**Comment by regevbr** [comment]
@upugo-dev sure go ahead and make a PR!

**Comment by upugo-dev** [comment]
https://github.com/PruvoNet/squiss-ts/pull/25
