### ISSUE TITLE
AWS BatchEntryIdsNotDistinct Error when deleting messages

### ISSUE THREAD

**Issue by upugo-dev** [PruvoNet/squiss-ts#26]
I am unable to delete message, at all. I am calling simply:

```
poller.on('message', (msg)=>{
  msg.del();
});
```

And my program crashes, recieving: 
`(node:15264) UnhandledPromiseRejectionWarning: AWS.SimpleQueueService.BatchEntryIdsNotDistinct: Id 9f9954d8-ac18-4892-b59b-a7ced5ddb382 repeated.`

**Comment by regevbr** [comment]
Intresting.
Let me check that,
Is there a way that you have called del() on the message a couple of times?

**Comment by upugo-dev** [comment]
Yeah, I realized what I was doing, I had the following settings:

```
visibilityTimeoutSecs: 1,
autoExtendTimeout: true,
advancedCallMs: 5,
noExtensionsAfterSecs: 10,
```

Which is probably faster than the latency of AWS right? So the message was recieving 1 request per s to delete. Now I have changed `visibilityTimeoutSecs: 10, noExtensionsAfterSecs: 100,` the program works as expected. 

Still, an interesting bug to get. Needs catching?

**Comment by regevbr** [comment]
Indeed, I will fix it right away. Thanks for letting me know about it

**Comment by upugo-dev** [comment]
As an aside, is there a way a message's properties can be inspected for it's deletion status? 

calling `poller.on('deleted', (msg)=>console.log(msg, 'deleted'));` does not log the message object, only the message identifier

It would be awesome if you could call `poller.on('handled', (msg)=>console.log(msg, 'handled'));` and inspect the handled msg object for some property that told you _how_ the message had been handled, for example `msg.handled = {deleted:true, kept:false, released:false}` or whatever

**Comment by regevbr** [comment]
The handled event if fired in 3 occasions:
1. deleted - which has its own event
2. release - which has its own event
3. keep -  which we can add an event for

So I think the best approach is just add an event for the `keep` event, so you can listen for events that are more specific - making your code more readable.

As to the deleted event - I agree we should send the msg itslef and not just the id but this is a breaking change and I will release a new major version for it.

If that sounds ok, please let me know and I will open new tickets for those features

**Comment by upugo-dev** [comment]
> As to the deleted event - I agree we should send the msg itslef and not just the id but this is a breaking change and I will release a new major version for it.

Yes I totally agree with this, this would be great!

**Comment by regevbr** [comment]
By the way the deleted event is also sent on the message itslef, so you can listen to it there and you will have the message as the context

**Comment by upugo-dev** [comment]
Ah perfect, thanks for the tip!

**Comment by regevbr** [comment]
@upugo-dev I fixed it, but please wait for the next release to get it

**Comment by upugo-dev** [comment]
awesome
