### ISSUE TITLE
Usage of Buffer constructor is deprecated in Node 10

### ISSUE THREAD

**Issue by jmac105** [PruvoNet/squiss-ts#67]
## Expected Behavior
squiss-ts should run without any runtime warnings

## Current Behavior
Usage of gzipUtils will cause warning messages to be logged due to `new Buffer()` being called. https://github.com/PruvoNet/squiss-ts/blob/master/src/gzipUtils.ts

See https://nodejs.org/docs/latest-v10.x/api/buffer.html#buffer_new_buffer_string_encoding

N.B. Also called in tests at https://github.com/PruvoNet/squiss-ts/blob/master/src/test/src/Message.spec.ts#L37 & https://github.com/PruvoNet/squiss-ts/blob/master/src/test/src/Message.spec.ts#L41

## Possible Solution
Replace Buffer constructor with Buffer.from()

## Steps to Reproduce (for bugs)
Run tests and check logs. See https://travis-ci.com/PruvoNet/squiss-ts/jobs/257131231#L250

## Context
No issues with usability, just a warning message in logs

## Your Environment

* Version used: latest
* Node version: >10

**Comment by regevbr** [comment]
@jmac105 thanks for reporting! I will get right on it

**Comment by regevbr** [comment]
@jmac105 v4.0.9 is released with the fix.
Please let me know if there is anything else I can help you with.
