### ISSUE TITLE
Consider migrating to the compression built into zlib

### ISSUE THREAD

**Issue by nathanpeck** [PruvoNet/squiss-ts#87]
This package still uses iltorb, which is no longer needed in modern versions of Node:

```
npm WARN deprecated iltorb@2.4.3: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
```

**Comment by regevbr** [comment]
Thanks for the issue submission. I want to support node 6 and above, so I can't remove iltorb as a dependency. Would you mind making a pr that will try to use zlib only if applicable?

**Comment by regevbr** [comment]
https://github.com/npm/npm/issues/7340 there is an idea there on how to install conditional dependencies

**Comment by regevbr** [comment]
https://stackoverflow.com/questions/44956778/conditional-postinstall-in-package-json-depending-on-your-os there ia an idea here as well

**Comment by regevbr** [comment]
@nathanpeck released in 4.1.0

**Comment by nathanpeck** [comment]
Awesome! Massive thanks for the fast turnaround time on that! I was
planning to PR but you beat me to it hah

**Comment by regevbr** [comment]
Haha you didn't respond so i figured you didn't have the time.
Glad to help!
If you like the library, a star would be much appreciated
