### ISSUE TITLE
License change?

### ISSUE THREAD

**Issue by thekiwi** [PruvoNet/squiss-ts#90]
**Is your feature request related to a problem? Please describe.**
We currently use [`sqs-consumer`](https://github.com/bbc/sqs-consumer) which is Apache 2.0 licensed. We really liked some of the features in [`squiss`](https://github.com/TomFrost/Squiss) which was ISC and were super excited to find this updated TypeScriptified fork. Unfortunately due to legal restrictions out of our control, we aren't able to use or contribute to GPL libraries, which means sadly we can't get involved with this library.

**Describe the solution you'd like**
I'd love for the repo to be relicensed as MIT, ISC or Apache 2.0. Appreciate it might be an impossible request but doesn't hurt to ask! 

**Describe alternatives you've considered**
As mentioned above:
- [`sqs-consumer`](https://github.com/bbc/sqs-consumer) - doesn't have concurrency utilization
- [`squiss`](https://github.com/TomFrost/Squiss) - unmaintained

**Additional context**
Before we noticed the license, we actually prototyped a solution using `squiss-ts` and it worked fantastically. So even if you are unable to change the license, I just wanted to say great effort on the library :)

**Comment by regevbr** [comment]
Sure will take care of it soon!

**Comment by regevbr** [comment]
@thekiwi thanks for your input!
I have changed the license to Apache 2.0 and it is released in 4.1.1
I'm glad to hear that my solution works for you!
Feel free to contact me if you have any other needs.

**Comment by thekiwi** [comment]
This is brilliant news! Many thanks @regevbr :)

**Comment by regevbr** [comment]
Sure thing @thekiwi, always happy to help!
