### ISSUE TITLE
Support for AWS SDK 3

### ISSUE THREAD

**Issue by javifraile** [PruvoNet/squiss-ts#95]
Are there any plans to support [`aws-sdk version 3`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html) of the AWS SDK? One of its perks is the modular architecture, it would reduce significantly the huge size of the dependency.

**Comment by regevbr** [comment]
@javifraile sadly they only support node >= 10 (which is more than acceptable) and I need this library to support node 6 and above... I can look into it if I can make the dependency dynamic or peered so you can control which version of the sdk you want to use

**Comment by regevbr** [comment]
I can use the same mechanism used in #88 to dynamically install the AWS sdk based on the node version

**Comment by javifraile** [comment]
> I can use the same mechanism used in #88 to dynamically install the AWS sdk based on the node version
That would be great! But I'm afraid is not simple such as change the number of version. We would have to check which modules are going to be used rather than install the whole package again, and check if there are breaking changes from one version to another.
I can have a look into this in the near future and open a PR if it's ok for you.

**Comment by regevbr** [comment]
We will need to create facades above the S3 and SQS APIs so the actual library being used will be non-relevant to the core code. I already added the logic to install different SDK based on the node version at https://github.com/PruvoNet/squiss-ts/tree/%2395
This will render the change to be quite massive as we will have to change many things. I will try to keep on working on it in the next couple of days. If I see I don't have the time for it, I will let you know so you can try to work on a PR yourself (which will be more than welcomed)

**Comment by regevbr** [comment]
fixed in https://github.com/PruvoNet/squiss-ts/releases/tag/v5.0.0
